@startuml
start
:Пользователь хочет купить улучшение;
if (достаточно монет?) then (да)
  :Уменьшить количество монет на 10;
  :В зависимости от выбранного улучшения
  улучшить одну из способностей героя;
else (нет)
endif
stop
@enduml
