@startuml
start
:Пользователь желает купить улучшение;
if (достаточно монет?) then (да)
  :Уменьшить количество монет на 10;
  :Применить выбранное улучшение к персонажу;
else (нет)
endif
stop
@enduml
