@startuml
start
:Пользователь стреляет;
if (есть патроны?) then (да)
  :Уменьшить количество патронов;
  while (пуля не исчезла?) is (да)  
  :пуля летит дальше;
  if (попадание во врага?) then (да)
    :Нанести урон врагу;
  else (нет)
    if (попадание в стену?) then (да)
      :Пуля исчезает;
      :Отображение количества патронов и статуса оружия;
      stop
    endif
  endif
  endwhile (нет)
else (нет)
  :Патроны закончились;
endif
:Отображение количества патронов и статуса оружия;
stop
@enduml