@startuml
start
:Пользователь стреляет;
:Отображение количества патронов и статуса оружия;
if (есть патроны?) then (да)
  :Пуля вылетает;
  :Уменьшить количество патронов;
  while (пуля не исчезла?) is (да)  
  :пуля летит дальше;
  if (столкновение с припятствием?) then (да) 
    if (попадание во врага?) then (да)
      :Нанести урон врагу;
    endif
    :Пуля исчезает;
  endif
  endwhile (нет)
else (нет)
  :Патроны закончились;
endif
stop
@enduml