@startuml
start
:Открытие меню;
while (Пользователь не нажмет на кнопку "START") is (true)
  :Ожидание;
endwhile
:Загрузка игрового уровня;
:Персонаж на верхней левой клетке лабиринта;
:Отображение лабиринта с врагами;
:Отображение информации о персонаже и оружии;
stop
@enduml
