@startuml
start

:Открытие меню;
  while (одна из кнопок нажата) is (нет)
    :Ожидание;
  endwhile
fork
  if (Это кнопка "START"?) then (да)
    :Построение лабиринта;
    :Размещение мобов;
    :Отображение информации о персонаже и оружии;
    :Начало игрового процесса;
  endif
fork again

  if (Это кнопка "SETTINGS"?) then (да)
    :Открытие окна настроек;
  endif
fork again
  if (Это кнопка "INFO"?) then (да)
    :Открыть руководство по игре;
  endif
endfork
stop
@enduml