@startuml

left to right direction
package "Игровое меню" {
    rectangle "Настроить громкость" as SetVolume
    rectangle "Узнать основные клавиши для перемещения и стрельбы" as GetControls
    rectangle "Начать игру" as StartGame
}

package "Управление персонажем" {
    rectangle "Перемещать персонажа" as MoveCharacter
    rectangle "Стрелять" as Shoot
}

package "Игровой процесс" {
    rectangle "Получать информацию о состоянии персонажа и оружия" as GetInfo
    rectangle "Покупать улучшения" as BuyUpgrades
    rectangle "Повышать уровень" as LevelUp
    rectangle "Убивать врагов" as KillEnemies
}

rectangle "Пользователь" as User

User --> SetVolume
User --> GetControls
User --> StartGame
User --> MoveCharacter
User --> Shoot
User --> GetInfo
User --> BuyUpgrades
User --> LevelUp

Shoot --> KillEnemies

@enduml
